### ISSUE TITLE
Port 80

### ISSUE THREAD

**Issue by kwamayze** [greggman/servez#3]
ERROR: listen EACCESS 0.0.0.0:80

**Comment by greggman** [comment]
I assume you're on Linux or macOS.

In that case you'd need to run as root to access port 80.

**Comment by kwamayze** [comment]
Yes Mac OS but i figured it out. I just used sudo together with servez. 
Having a very weird problem that my server will download at 1KB/s with python or node
Thank you for the reply

**Comment by patrickhlauke** [comment]
Randomly: this issue can probably be closed?

**Comment by greggman** [comment]
I left it open incase I want to try to add an option to make it work without sudo.

**Comment by test2a** [comment]
sudo ./Servez-1.7.0.AppImage -p:80
>[763950:1027/104513.374112:FATAL:electron_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap

sudo ./Servez-1.7.0.AppImage -p:80 --no-sandbox
>Error: Invalid option '--sandbox' - perhaps you meant '--index'?
    at getOption (/tmp/.mount_Servezi7Jybj/resources/app.asar/node_modules/optionator/lib/index.js:169:15)
    at Object.parse (/tmp/.mount_Servezi7Jybj/resources/app.asar/node_modules/optionator/lib/index.js:396:23)
    at Object.<anonymous> (/tmp/.mount_Servezi7Jybj/resources/app.asar/main.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (electron/js2c/browser_init.js:5805:12)
Usage: servez [options] path-to-serve

    -h, --help     : displays help
    -p, --port=Int : port - default: 8080
    --no-dirs      : show directory listing
    --no-cors      : send CORS headers
    --ssl          : use HTTPS - default: false
    --local        : local machine only - default: false
    --no-index     : serve index.html for directories

**Comment by test2a** [comment]
i want to run server at port 80 but i am not being able to.

**Comment by greggman** [comment]
If you want an instant solution use [the command line version of servez](https://github.com/greggman/servez-cli)
I can try to make the app version work but don't know when I'll be able to get around to it.

It's also possible this might work

```
sudo ./Servez-1.7.0.AppImage --no-sandbox -- -p:80 
```

but I didn't try it

**Comment by test2a** [comment]
![Screenshot_20201027_143117](https://user-images.githubusercontent.com/39449563/97279589-30874d80-1861-11eb-8d4c-592afb15fd09.png)
ok. it worked but kinda. the default folder is changed to port which would not work and port in the box defaulted to 8080. changing the path and port to 80 worked. Maybe you can improve on this? thanks for the quick response anyways, this should be enough for my work.

edit: 
btw, i used this
> sudo ./Servez-1.7.0.AppImage --no-sandbox -- -p:80
